## EXPERIMENT 2: Using Numpy

### PROBLEM 1: Normalization

In [5]:
import numpy as np

# Create a random 5x5 ndarray named X with values in the range (0, 50)
X = np.random.randint(0, 50, (5, 5))

# Calculate the mean and standard deviation
mean = np.mean(X)
std = np.std(X)

# Calculate the z-score 
X_normalized = (X - mean) / std

# Save the normalized array to a file
np.save('X_normalized.npy', X_normalized)

# Print the normalized array
print("Normalized X:\n", X_normalized)

Normalized X:
 [[ 1.05529866  1.56510478  0.41804102 -1.1751031  -0.60157122]
 [ 1.37392748 -1.43000616  0.92784713 -1.23882886  0.8003956 ]
 [ 1.56510478 -1.1751031  -1.49373192 -0.02803934 -0.15549087]
 [ 0.8003956  -1.55745769 -0.98392581  0.29058949 -0.0917651 ]
 [ 0.67294407  0.60921831 -0.72902275 -0.34666816  0.92784713]]


### PROBLEM 2: Indexing of Arrays

In [9]:
# Create a 10x10 array with values from 1 to 100
A = np.arange(1, 101).reshape(10, 10)

# Square all elements in the array
squared_A = A ** 2

# Use modulus operation and boolean indexing to get elements divisible by 3
div_by_3 = squared_A[squared_A % 3 == 0]

# Save the result to a file
np.save('div_by_3.npy', div_by_3)

# Print elements divisible by 3 in squared_A
print("Elements divisible by 3:", div_by_3)


Elements divisible by 3: [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
